version: "3"

services:
  server:
    build: ./
    container_name: twigir-server
    restart: always
    ports:
      - '8035:8035'
    depends_on:
      - redis
    links:
      - redis
    networks:
      - back
  redis:
    image: redis:alpine
    container_name: redis # 容器名
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - /home/twigir/redis:/data
    networks:
      - back
networks:
  back: